<?php
/** @var Orba_Yotpo_Helper_Data $_helper */
$_helper = Mage::helper('DisplayFeedback/data');
$_tabContent = $_helper->getJsonReviewTabContent();
$_content = $_helper->getJsonReviewContent();
?>
<script language="javascript"> var objJson = <?= $_content;?>;</script>
<div class="stickysidebar" id="open-modal" data-triger="modal-1">
    <p><?= $_tabContent;?></p>
</div>
<div class="modal-wrap" id="modal-1">
	<button class="close-modal">&times;</button>
	<div class="modal-container">
	  <div class="modal-content">
	  	<h3>Customer Reviews</h3>
	    <div id="reviewComments"></div>
	    <div class="feedback_pager">
			<a href="javascript:prevPage(objJson)" id="btn_prev">Prev</a>
			<span id="page"></span>
			<a href="javascript:nextPage(objJson)" id="btn_next">Next</a>
		</div>
	  </div>
	</div>
</div>
<script language="javascript"> changePage(1, objJson);</script>
